name: CI
on:
  pull_request:
    branchs: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use NodeS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm run test -- --coverage
        env:
          CI: true
    